.PHONY: all

all: 06-exemplos.zip 10-exemplos.zip

06-exemplos.zip: triangulo.py bola-bate-volta.py bola-controle.py
	zip 06-exemplos.zip triangulo.py bola-bate-volta.py bola-controle.py

10-exemplos.zip: 10/*
	zip 10-exemplos.zip 10/*
